import React from "react";
import '../styles/picform.css'

const Archi = () => {
  return (
    <>
      <div className="main">
        <div className="main-name">
          <h2>Archeological Photography</h2>
          <div className="pop">
            <img
              className="image-fluid2"
              src="images/archi/a1.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a25.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a3.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a4.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a5.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a6.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a7.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a8.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a9.jpeg"
              height="300px"
              width="400px"
            />
          </div>
          <div className="back">
            <img
              className="image-fluid3"
              id="spa"
              src="images/archi/a15.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/archi/a10.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/archi/a11.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              id="spa"
              src="images/archi/a12.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/archi/a13.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/archi/a14.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              id="spa"
              src="images/archi/a16.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/archi/a17.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/archi/a18.jpeg"
              height="300px"
              width="400px"
            />
          </div>
          <div className="pop">
            <img
              className="image-fluid2"
              src="images/archi/a19.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a20.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a21.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a22.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a23.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a24.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a2.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a26.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/archi/a27.jpeg"
              height="300px"
              width="400px"
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default Archi;
