import React from "react";
import "../styles/picform.css";

const Event = () => {
  return (
    <>
      <div className="main">
        <div className="main-name">
          <h2>Events Photography</h2>
          <div className="pop">
            <img
              className="image-fluid2"
              src="images/event/e1.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e2.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e3.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e4.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e5.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e6.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e7.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e8.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e9.jpeg"
              height="300px"
              width="400px"
            />
          </div>
          <div className="back">
            <img
              className="image-fluid3"
              id="spa"
              src="images/event/e10.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/event/e11.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/event/e12.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              id="spa"
              src="images/event/e13.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/event/e14.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/event/e15.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              id="spa"
              src="images/event/e16.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/event/e17.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/event/e18.jpeg"
              height="300px"
              width="400px"
            />
          </div>
          <div className="pop">
            <img
              className="image-fluid2"
              src="images/event/e20.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e21.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e22.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e23.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e24.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e25.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e19.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e26.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/event/e27.jpeg"
              height="300px"
              width="400px"
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default Event;
