import React from 'react'
import "../styles/work.css"

const Gallery = () => {
  return (
    <>
<div className="main">
  <div className="workname">
    <p id="nmae">Gallery</p>
  </div>
  <div className="photograph-display">
    <img
      className="image-fluid"
      src="images/display01.jpg"
      height="300px"
      width="190px"
    />
    <img
      className="image-fluid"
      src="images/display02.jpeg"
      height="300px"
      width="210px"
    />
    <img
      className="image-fluid"
      src="images/display03.jpg"
      height="300px"
      width="200px"
    />
    <img
      className="image-fluid"
      src="images/display04.webp"
      height="300px"
      width="210px"
    />
    <img
      className="image-fluid"
      src="images/display05.jpeg"
      height="300px"
      width="200px"
    />
    <img
      className="image-fluid"
      src="images/display06.jpg"
      height="300px"
      width="181px"
    />
  </div>
  <div className="fea">
    <h3 id="name">Featured Gallery</h3>
    <div className="tags">
      <div className="container-img">
        <div className="blur-img">
          <a href="potrait.html">
            <img
              className="image-fluid1"
              src="images/potrait/po22.jpeg"
              height="300px"
              width="200px"
            />
          </a>
        </div>
        <div className="middle">
          <div className="text">Potrait</div>
        </div>
      </div>
      <div className="container-img">
        <div className="blur-img">
          <a href="landscape.html">
            <img
              className="image-fluid1"
              src="images/landscape/ls7.jpeg"
              height="300px"
              width="200px"
            />
          </a>
        </div>
        <div className="middle">
          <div className="text">Landscape</div>
        </div>
      </div>
      <div className="container-img">
        <div className="blur-img">
          <a href="sports.html">
            <img
              className="image-fluid1"
              src="images/sports/spo22.jpeg"
              height="300px"
              width="200px"
            />
          </a>
        </div>
        <div className="middle">
          <div className="text">Sports</div>
        </div>
      </div>
      <div className="container-img">
        <div className="blur-img">
          <a href="Event.html">
            <img
              className="image-fluid1"
              src="images/event/e22.jpeg"
              height="300px"
              width="200px"
            />
          </a>
        </div>
        <div className="middle">
          <div className="text">Events</div>
        </div>
      </div>
      <div className="container-img">
        <div className="blur-img">
          <a href="wildlife.html">
            <img
              className="image-fluid1"
              src="images/wildlife/wf22.jpeg"
              height="300px"
              width="200px"
            />
          </a>
        </div>
        <div className="middle">
          <div className="text">Wildlife</div>
        </div>
      </div>
      <div className="container-img">
        <div className="blur-img">
          <a href="archi.html">
            <img
              className="image-fluid1"
              src="images/archi/a22.jpeg"
              height="300px"
              width="200px"
            />
          </a>
        </div>
        <div className="middle">
          <div className="text">Archeological</div>
        </div>
      </div>
    </div>
  </div>
  <div className="dis">
    <h3 className="nm">Featured Images</h3>
    <div className="pop">
      <img
        className="image-fluid2"
        src="images/bg4.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/bg3.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/icon2.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/wild.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/display03.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/wedd.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/po7.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo12.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/potrait/po25.jpeg"
        height="300px"
        width="400px"
      />
    </div>
    <div className="back">
      <img
        className="image-fluid3"
        id="spa"
        src="images/sports/spo6.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/archi/a24.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/potrait/pot16.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        id="spa"
        src="images/sports/spo13.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/landscape/ls2.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/event/e19.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        id="spa"
        src="images/po1.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/icon3.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/landscape/ls1.jpeg"
        height="300px"
        width="400px"
      />
    </div>
    <div className="pop">
      <img
        className="image-fluid2"
        src="images/archi/a13.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/potrait/po4.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo17.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/potrait/po26.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/landscape/ls7.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/inpic.webp"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/landscape/ls4.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/wildlife/wf25.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/wildlife/wf12.jpeg"
        height="300px"
        width="400px"
      />
    </div>
    <div className="back">
      <img
        className="image-fluid3"
        id="spa"
        src="images/potrait/pot20.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/landscape/ls12.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/wildlife/wf10.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        id="spa"
        src="images/event/e15.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/archi/a3.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/event/e4.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        id="spa"
        src="images/slide02.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/archi/a17.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/po5.jpg"
        height="300px"
        width="400px"
      />
    </div>
    <div className="pop">
      <img
        className="image-fluid2"
        src="images/archi/a3.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/potrait/pot19.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo19.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/event/e19.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/landscape/ls11.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo11.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/icon1.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/wildlife/wf17.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/wildlife/wf11.jpeg"
        height="300px"
        width="400px"
      />
    </div>
    <div className="back">
      <img
        className="image-fluid3"
        id="spa"
        src="images/potrait/pot9.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/landscape/ls5.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/wildlife/wf25.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        id="spa"
        src="images/event/e25.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/archi/a25.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/event/e5.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        id="spa"
        src="images/wildlife/wf15.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/archi/a13.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/wildlife/wf16.jpeg"
        height="300px"
        width="400px"
      />
    </div>
    <div className="pop">
      <img
        className="image-fluid2"
        src="images/archi/a4.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/potrait/po4.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo4.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/event/e4.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/landscape/ls4.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo8.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/po4.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/wildlife/wf4.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/wildlife/wf18.jpeg"
        height="300px"
        width="400px"
      />
    </div>
  </div>
</div>

    </>
  )
}

export default Gallery