import React from 'react'
import "../styles/picform.css";

const Landscape = () => {
  return (
    <>
    <div className="main">
  <div className="main-name">
    <h2>Landscape Photography</h2>
    <div className="pop">
      <img
        className="image-fluid2"
        src="images/bg2.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/bg3.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/bg4.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/bg5.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/display04.webp"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/display05.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/enq.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/enquire.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/slide02.jpg"
        height="300px"
        width="400px"
      />
    </div>
    <div className="back">
      <img
        className="image-fluid3"
        id="spa"
        src="images/landscape/ls1.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/landscape/ls2.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/landscape/ls3.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        id="spa"
        src="images/landscape/ls4.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/landscape/ls5.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/landscape/ls6.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        id="spa"
        src="images/landscape/ls7.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/landscape/ls8.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/landscape/ls9.jpeg"
        height="300px"
        width="400px"
      />
    </div>
    <div className="pop">
      <img
        className="image-fluid2"
        src="images/landscape/ls10.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/landscape/ls11.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/landscape/ls12.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/landscape/ls13.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/landscape/ls14.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/landscape/ls15.jpg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/landscape/ls16.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/landscape/ls17.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/icon2.jpg"
        height="300px"
        width="400px"
      />
    </div>
  </div>
</div>

    </>
  )
}

export default Landscape