import React from "react";
import '../styles/picform.css'

const Portrait = () => {
  return (
    <>
      <div className="main">
        <div className="main-name">
          <h2>Portrait Photography</h2>
          <div className="pop">
            <img
              className="image-fluid2"
              src="images/potrait/pot1.jpg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/pot2.jpg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/pot3.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/po4.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/pot5.jpg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/pot6.jpg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/po7.jpg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/pot8.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/pot9.jpg"
              height="300px"
              width="400px"
            />
          </div>
          <div className="back">
            <img
              className="image-fluid3"
              id="spa"
              src="images/potrait/po10.jpg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/potrait/pot11.webp"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/potrait/pot12.jpg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              id="spa"
              src="images/potrait/pot13.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/potrait/pot14.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/potrait/pot15.jpg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              id="spa"
              src="images/potrait/pot16.jpg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/potrait/pot17.jpg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/potrait/pot18.jpg"
              height="300px"
              width="400px"
            />
          </div>
          <div className="pop">
            <img
              className="image-fluid2"
              src="images/potrait/pot19.jpg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/pot20.jpg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/po22.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/po23.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/po24.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/po25.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/po26.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/pot21.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/potrait/po27.jpeg"
              height="300px"
              width="400px"
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default Portrait;
