import React from 'react'
import '../styles/picform.css'

const Sports = () => {
  return (
    <>
<div className="main">
  <div className="main-name">
    <h2>Sports Photography</h2>
    <div className="pop">
      <img
        className="image-fluid2"
        src="images/sports/spo1.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo2.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo3.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo4.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo5.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo6.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo7.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo8.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo9.jpeg"
        height="300px"
        width="400px"
      />
    </div>
    <div className="back">
      <img
        className="image-fluid3"
        id="spa"
        src="images/sports/spo10.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/sports/spo11.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/sports/spo12.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        id="spa"
        src="images/sports/spo13.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/sports/spo14.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/sports/spo15.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        id="spa"
        src="images/sports/spo16.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/sports/spo17.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid3"
        src="images/sports/spo18.jpeg"
        height="300px"
        width="400px"
      />
    </div>
    <div className="pop">
      <img
        className="image-fluid2"
        src="images/sports/spo19.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo20.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo21.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo22.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo23.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo24.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo25.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo26.jpeg"
        height="300px"
        width="400px"
      />
      <img
        className="image-fluid2"
        src="images/sports/spo27.jpeg"
        height="300px"
        width="400px"
      />
    </div>
  </div>
</div>

    </>
  )
}

export default Sports