import React from "react";
import "../styles/picform.css";

const Wildlife = () => {
  return (
    <>
      <div className="main">
        <div className="main-name">
          <h2>Wildlife Photography</h2>
          <div className="pop">
            <img
              className="image-fluid2"
              src="images/wildlife/wf1.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf2.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf3.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf4.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf6.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf5.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf7.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf8.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf9.jpeg"
              height="300px"
              width="400px"
            />
          </div>
          <div className="back">
            <img
              className="image-fluid3"
              id="spa"
              src="images/wildlife/wf10.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/wildlife/wf11.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/wildlife/wf12.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              id="spa"
              src="images/wildlife/wf13.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/wildlife/wf14.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/wildlife/wf15.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              id="spa"
              src="images/wildlife/wf16.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/wildlife/wf17.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid3"
              src="images/wildlife/wf18.jpeg"
              height="300px"
              width="400px"
            />
          </div>
          <div className="pop">
            <img
              className="image-fluid2"
              src="images/wildlife/wf19.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf20.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf21.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf22.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf23.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf24.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf25.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf26.jpeg"
              height="300px"
              width="400px"
            />
            <img
              className="image-fluid2"
              src="images/wildlife/wf27.jpeg"
              height="300px"
              width="400px"
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default Wildlife;
